In [0]:
#@title Authenticate user
from google.colab import auth
auth.authenticate_user()

In [0]:
#@title Pull OpenAQ data via BigQuery
%%bigquery --project silicon-perigee-208521 p
#standardSQL
select
  pollutant,
  country,
  city,
  location,
  value
from `bigquery-public-data.openaq.global_air_quality`;

,pollutant,country,city,location,value
0,pm25,US,007,Plain_Mobile,0.000000
1,pm25,US,007,Cle Elum_Mobile,0.000000
2,pm25,US,007,Leavenworth_Mobile,10.000000
3,pm25,US,037,Mobile_Cle Elum,62.000000
4,pm25,US,039,Mobile_WhiteSalmon,58.000000
5,pm25,US,047,Brewster_Mobile,7.000000
6,pm25,US,051,Mobile_Newport,29.000000
7,pm25,US,051,Newport_Mobile,-2.000000
8,pm25,US,051,Mobile_Newport_2017,26.000000
9,co,US,ADA,Near Road,0.290000
10,bc,US,ADA,Near Road,0.600000
11,no2,US,ADA,Near Road,0.008000
12,pm25,US,ADA,Near Road,12.000000
13,pm10,US,ADA,Near Road,46.000000
14,o3,FR,Ain,FR33305,136.000000
15,pm10,FR,Ain,FR33305,34.830000
16,no2,FR,Ain,FR33305,66.800000
17,o3,FR,Ain,COTIERE AIN,128.350000
18,no2,FR,Ain,COTIERE AIN,3.750000
19,pm10,FR,Ain,COTIERE AIN,21.280000
20,pm25,US,FRA,MMFRA1001,8.000000
21,pm25,US,GBU,GBUAPCD EBAM 1,3.000000
22,pm25,US,GBU,GBUAPCD EBAM @ Coso,20.000000
23,pm25,US,GBU,GBUAPCD EBAM @ June,-2.000000
24,pm25,US,GBU,GBUAPCD EBAM @ Alpin,14.000000
25,pm25,US,GBU,GBUAPCD EBAM @ Bisho,1.000000
26,pm25,US,GBU,GBUAPCD EBAM @ Bridg,4.000000
27,pm25,US,GBU,GBUAPCD EBAM @ Crowl,12.000000
28,pm25,US,GBU,GBUAPCD EBAM @ Lee V,5.000000
29,so2,US,KAY,Ponca City,0.000000
...,...,...,...,...,...
25170,no2,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,3.804000
25171,so2,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,3.573000
25172,pm25,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,12.185000
25173,o3,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,57.693000
25174,o3,HR,Državna mreža za trajno praćenje kvalitete zra...,ŽARKOVICA (Dubrovnik) - RH0120 - HR0020A; Drža...,59.200000
25175,no2,HR,Državna mreža za trajno praćenje kvalitete zra...,ŽARKOVICA (Dubrovnik) - RH0120 - HR0020A; Drža...,0.900000
25176,pm10,HU,Hungarian Regional Background Air Pollution M...,K-puszta,32.600000
25177,no2,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,26.800000
25178,so2,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,5.300000
25179,co,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,350.000000
25180,no2,GI,UK Air Quality e-Reporting monitoring network ...,Bleak House,24.900000
25181,o3,GI,UK Air Quality e-Reporting monitoring network ...,Bleak House,55.900000
25182,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Laois Emo Court,35.150000
25183,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Laois Emo Court,3.438000
25184,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Clare Ennis Simms Lane,1.862000
25185,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Kilkenny Seville Lodge,0.191000
25186,co,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.345422
25187,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.000000
25188,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.000000
25189,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Winetavern Street,0.000000
25190,co,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Winetavern Street,0.198059
25191,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Monaghan Kilkitt Waterworks,2.726500
25192,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Monaghan Kilkitt Waterworks,1.528000
25193,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Mayo Castlebar John Moore Road,37.950000
25194,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Clonskeagh Road Richview,42.784000
25195,pm25,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,0.377067
25196,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,9.836500
25197,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,18.050000
25198,pm10,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,2.238530
25199,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,1.662500

In [0]:
#@title For each pollutant, calculate rank of each location within its country and world-wide 
# Rank within world
p = p.assign(world_rank=(
      p.groupby(['pollutant'])['value']
        .rank(method='min', ascending=False)
        .astype(int)))
# Rank within country
p = p.assign(country_rank=(
      p.groupby(['pollutant', 'country'])['value']
        .rank(method='min', ascending=False)
        .astype(int)))
# Rank within city
p = p.assign(city_rank=(
      p.groupby(['pollutant', 'country', 'city'])['value']
        .rank(method='min', ascending=False)
        .astype(int)))
p

,pollutant,country,city,location,value,world_rank,country_rank,city_rank
0,pm25,US,007,Plain_Mobile,0.000000,3757,964,2
1,pm25,US,007,Cle Elum_Mobile,0.000000,3757,964,2
2,pm25,US,007,Leavenworth_Mobile,10.000000,2222,253,1
3,pm25,US,037,Mobile_Cle Elum,62.000000,523,4,1
4,pm25,US,039,Mobile_WhiteSalmon,58.000000,556,5,1
5,pm25,US,047,Brewster_Mobile,7.000000,2631,435,1
6,pm25,US,051,Mobile_Newport,29.000000,1079,35,1
7,pm25,US,051,Newport_Mobile,-2.000000,3858,1009,3
8,pm25,US,051,Mobile_Newport_2017,26.000000,1191,40,2
9,co,US,ADA,Near Road,0.290000,2453,85,1
10,bc,US,ADA,Near Road,0.600000,49,6,1
11,no2,US,ADA,Near Road,0.008000,4541,121,1
12,pm25,US,ADA,Near Road,12.000000,2025,194,1
13,pm10,US,ADA,Near Road,46.000000,1213,13,1
14,o3,FR,Ain,FR33305,136.000000,46,11,1
15,pm10,FR,Ain,FR33305,34.830000,1646,56,1
16,no2,FR,Ain,FR33305,66.800000,301,41,1
17,o3,FR,Ain,COTIERE AIN,128.350000,78,26,2
18,no2,FR,Ain,COTIERE AIN,3.750000,3996,429,2
19,pm10,FR,Ain,COTIERE AIN,21.280000,2501,162,2
20,pm25,US,FRA,MMFRA1001,8.000000,2476,372,1
21,pm25,US,GBU,GBUAPCD EBAM 1,3.000000,3343,772,6
22,pm25,US,GBU,GBUAPCD EBAM @ Coso,20.000000,1490,62,1
23,pm25,US,GBU,GBUAPCD EBAM @ June,-2.000000,3858,1009,8
24,pm25,US,GBU,GBUAPCD EBAM @ Alpin,14.000000,1854,147,2
25,pm25,US,GBU,GBUAPCD EBAM @ Bisho,1.000000,3657,915,7
26,pm25,US,GBU,GBUAPCD EBAM @ Bridg,4.000000,3137,693,5
27,pm25,US,GBU,GBUAPCD EBAM @ Crowl,12.000000,2025,194,3
28,pm25,US,GBU,GBUAPCD EBAM @ Lee V,5.000000,2964,605,4
29,so2,US,KAY,Ponca City,0.000000,3250,116,1
...,...,...,...,...,...,...,...,...
25170,no2,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,3.804000,3993,7,4
25171,so2,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,3.573000,1876,1,1
25172,pm25,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,12.185000,2022,3,1
25173,o3,HR,Državna mreža za trajno praćenje kvalitete zra...,SLAVONSKI BROD-1 - RH0109 - HR0010A; Državna m...,57.693000,1703,5,4
25174,o3,HR,Državna mreža za trajno praćenje kvalitete zra...,ŽARKOVICA (Dubrovnik) - RH0120 - HR0020A; Drža...,59.200000,1616,4,3
25175,no2,HR,Državna mreža za trajno praćenje kvalitete zra...,ŽARKOVICA (Dubrovnik) - RH0120 - HR0020A; Drža...,0.900000,4238,10,5
25176,pm10,HU,Hungarian Regional Background Air Pollution M...,K-puszta,32.600000,1751,8,1
25177,no2,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,26.800000,1675,2,1
25178,so2,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,5.300000,1368,1,1
25179,co,GI,UK Air Quality e-Reporting monitoring network ...,Rosia Road,350.000000,1782,1,1
25180,no2,GI,UK Air Quality e-Reporting monitoring network ...,Bleak House,24.900000,1769,3,2
25181,o3,GI,UK Air Quality e-Reporting monitoring network ...,Bleak House,55.900000,1777,1,1
25182,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Laois Emo Court,35.150000,2415,9,3
25183,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Laois Emo Court,3.438000,4014,10,2
25184,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Clare Ennis Simms Lane,1.862000,2414,4,2
25185,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Kilkenny Seville Lodge,0.191000,4257,12,4
25186,co,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.345422,2397,1,1
25187,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.000000,3250,7,4
25188,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Coleraine Street,0.000000,4862,13,5
25189,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Winetavern Street,0.000000,3250,7,4
25190,co,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Winetavern Street,0.198059,2548,2,2
25191,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Monaghan Kilkitt Waterworks,2.726500,2163,3,1
25192,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Monaghan Kilkitt Waterworks,1.528000,4194,11,3
25193,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Mayo Castlebar John Moore Road,37.950000,2362,8,2
25194,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Clonskeagh Road Richview,42.784000,2215,7,1
25195,pm25,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,0.377067,3740,5,1
25196,no2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,9.836500,3194,7,1
25197,o3,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,18.050000,2771,11,4
25198,pm10,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,2.238530,4276,10,1
25199,so2,IE,Ireland Air Quality e-Reporting monitoring net...,Dublin Rathmines Wynnefield Road,1.662500,2433,5,3

In [0]:
#@title Pollutants in dataset
print(', '.join(p['pollutant'].unique()))

pm25, co, bc, no2, pm10, o3, so2

In [0]:
#@title Top three locations by Nitrogen Dioxide (NO2)
(p.query('pollutant == "no2"')
  .nsmallest(3, 'world_rank')
  [['country', 'city', 'location', 'value', 'world_rank']])

,country,city,location,value,world_rank
19239,XK,Hani i Elezit,Hani i Elezit,397.926,1
6078,IN,Solapur,"Solapur, Solapur - MPCB",268.360,2
16204,IN,Kalaburagi,"Lal Bahadur Shastri Nagar, Kalaburagi - KSPCB",229.210,3

In [0]:
#@title Top three locations in Great Britain by Nitrogen Dioxide (NO2)
(p.query('pollutant == "no2" & country == "GB"')
  .nsmallest(3, 'country_rank')
  [['city', 'location', 'value', 'world_rank', 'country_rank']])

,city,location,value,world_rank,country_rank
4585,Belfast,Belfast Stockman's Lane,63.0,359,1
6707,Chepstow,Chepstow A48,60.0,418,2
6442,Aberdeen,Aberdeen Union Street Roadside,54.0,544,3

In [0]:
#@title Top three locations by Sulphur Dioxide (SO2)
(p.query('pollutant == "so2"')
  .nsmallest(3, 'world_rank')
  [['country', 'city', 'location', 'value', 'world_rank']])

,country,city,location,value,world_rank
24629,MK,State Air Quality Monitoring Network,Karpos,2.050019e+15,1
7092,CL,Hualpén,JUNJI,2.088350e+03,2
3412,ES,Murcia,ES1633A,1.301000e+03,3

In [0]:
#@title Top three locations in Great Britain by Sulphur Dioxide (SO2)
(p.query('pollutant == "so2" & country == "GB"')
  .nsmallest(3, 'country_rank')
  [['city', 'location', 'value', 'world_rank', 'country_rank']])

                city            location  value  world_rank  country_rank
19339  Middlesbrough       Middlesbrough   19.0         323             1
17408    Southampton  Southampton Centre   14.0         497             2
1188           Derry     Derry Rosemount   13.0         545             3

In [0]:
#@title Top three locations by PM2.5
(p.query('pollutant == "pm25"')
  .nsmallest(3, 'world_rank')
  [['country', 'city', 'location', 'value', 'world_rank']])

,country,city,location,value,world_rank
9849,CN,义乌市,江东,690.0,1
1695,IN,Patna,"IGSC Planetarium Complex, Patna - BSPCB",674.0,2
9845,CN,义乌市,北苑,494.0,3

In [0]:
#@title Top three locations in Great Britain by PM2.5
(p.query('pollutant == "pm25" & country == "GB"')
  .nsmallest(3, 'country_rank')
  [['city', 'location', 'value', 'world_rank', 'country_rank']])

,city,location,value,world_rank,country_rank
17442,Storrington,Storrington Roadside,62.0,523,1
19611,West Midlands,Birmingham A4540 Roadside,28.0,1118,2
8973,Newcastle,Newcastle Centre,17.0,1672,3

In [0]:
#@title Compare the worst locations (NO2) in Great Britain and Sweden
(p.query('pollutant == "no2"')
  .query('country_rank == 1')
  .query('(country == "GB") | (country == "SE")')
  [['country', 'city', 'location', 'value', 'world_rank', 'country_rank']])

,country,city,location,value,world_rank,country_rank
4585,GB,Belfast,Belfast Stockman's Lane,63.0000,359,1
9241,SE,Stockholm,Sveavägen,42.6175,917,1

Note that we can also do a lot of the work using BigQuery. But since the dataset is fairly small, we don't need to do that. Example on how to compute the rank in BigQuery:

In [0]:
#@title Rank cities within each country for each pollutant
%%bigquery --project silicon-perigee-208521
#standardSQL
select
  pollutant,
  country,
  city,
  location,
  value,
  rank() over (
    partition by
      pollutant,
      country
    order by value desc) as world_rank
from `bigquery-public-data.openaq.global_air_quality`;

,pollutant,country,city,location,value,world_rank
0,bc,PL,Kielce,"Kielce, ul. Targowa",5.73000,1
1,bc,PL,Rybnik,"Rybnik, ul. Borki 37 d",5.27091,2
2,bc,PL,Nowy Targ,"Nowy Targ, Plac Słowackiego",4.70168,3
3,bc,PL,Czerwionka-Leszczyny,"Czerwionka-Leszczyny, ul. Kopalniana",4.24980,4
4,bc,PL,Zamość,Zamość ul. Hrubieszowska 69A,2.98000,5
5,bc,PL,Zgorzelec,Zgorzelec - Bohaterów Getta,2.79247,6
6,bc,PL,Mielec,Mielec-Biernackiego-WIOS,2.44703,7
7,bc,PL,Łódź,Łódź-Gdańska 16,2.40000,8
8,bc,PL,Radom,Radom-Tochtermana,2.13700,9
9,bc,PL,Starachowice,"Starachowice, ul. Złota",2.05000,10
10,bc,PL,Nałęczów,NałęczówMOB,1.83000,11
11,bc,PL,Elbląg,WIOŚ Elbląg ul. Bażyńskiego,1.71441,12
12,bc,PL,Ciechocinek,Ciechocinek,1.67000,13
13,bc,PL,Olsztyn,WIOŚ Olsztyn ul. Puszkina,1.60116,14
14,bc,PL,Lublin,Lublin ul. Obywatelska,1.58000,15
15,bc,PL,Poznań,Poznan-Dabrowskiego,1.54602,16
16,bc,PL,Żary,"Żary, ul. Szymanowskiego 8",1.52208,17
17,bc,PL,Dąbrowa Górnicza,"Dąbrowa Górnicza, ul. Tysiąclecia 25a",1.47895,18
18,bc,PL,Zakopane,"Zakopane, ul. Sienkiewicza",1.40855,19
19,bc,PL,Bydgoszcz,Bydgoszcz Plac Poznański,1.40000,20
20,bc,PL,Złoty Potok,"Złoty Potok, Leśniczówka",1.30888,21
21,bc,PL,Rzeszów,Rzeszów-Piłsudskiego,1.28196,22
22,bc,PL,Legnica,Legnica - Rzeczypospolitej,1.24425,23
23,bc,PL,Jelenia Góra,Jelenia Góra - Ogińskiego,1.22316,24
24,bc,PL,Rzeszów,Rzeszów-Nowe Miasto,1.20132,25
25,bc,PL,Kędzierzyn-Koźle,K-Koźle automat 1,1.17559,26
26,bc,PL,Zdzieszowice,Zdzieszowice automat 2,1.07319,27
27,bc,PL,Kraków,"Kraków, ul. Bujaka",1.04718,28
28,bc,PL,Opole,Opole manualna 4,0.95039,29
29,bc,PL,Gdańsk,AM2 Gdańsk Stogi,0.95039,29
...,...,...,...,...,...,...
25170,so2,US,Honolulu,Kapolei,0.00000,116
25171,so2,US,Honolulu,Honolulu,0.00000,116
25172,so2,US,Lakeland,Sikes Elementary Sch,0.00000,116
25173,so2,US,Muskogee,Muskogee,0.00000,116
25174,so2,US,Muskogee,Ft. Gibson,0.00000,116
25175,so2,US,Richmond,SHIRLEY PLANTATION,0.00000,116
25176,so2,US,Sheridan,Sheridan Mobile,0.00000,116
25177,so2,US,ARCHULETA,7004,0.00000,116
25178,so2,US,AROOSTOOK,MICMAC,0.00000,116
25179,so2,US,Asheville,Skyland DRR,0.00000,116
25180,so2,US,Houston,Clinton C403/C304/AH113,-0.00010,282
25181,so2,US,Houston-Sugar Land-Baytown,Houston Croquet C409,-0.00010,282
25182,so2,US,Houston,Baytown Garth C1017,-0.00010,282
25183,so2,US,Houston,Park Place C416,-0.00020,285
25184,so2,US,Houston,Houston Monroe C406,-0.00040,286
25185,so2,US,Kingsport-Bristol-Bristol,Andrew Johnson Elem.,-0.00100,287
25186,so2,US,Cheyenne,Cheyenne Mobile,-0.00100,287
25187,so2,US,Evansville,Evansville-Buena Vis,-0.00100,287
25188,so2,US,Birmingham-Hoover,LNA,-0.00100,287
25189,so2,US,LEE,Blackstone,-0.00100,287
25190,so2,XK,Prishtine,"Prishtine, Rilindje",23.35600,1
25191,so2,XK,Gjilan,Gjilan,16.40000,2
25192,so2,XK,Prizren,Prizren,6.46100,3
25193,so2,XK,Drenas,Drenas,6.36600,4
25194,so2,XK,Mitrovice,Mitrovice,5.89200,5
25195,so2,XK,Prishtine,Prishtine - IHMK,1.79600,6
25196,so2,XK,Hani i Elezit,Hani i Elezit,1.57400,7
25197,so2,ZA,Richards Bay,Brackenham,0.00180,1
25198,so2,ZA,Richards Bay,Arboretum,-0.00090,2
25199,so2,ZA,Richards Bay,CBD,-0.00190,3